EventScript_UseSurf::
	goto_if_questlog EventScript_UseSurfEnd
	goto_if_unset FLAG_GOT_HM03, EventScript_UseSurfEnd
	bufferpartymonnick STR_VAR_1, 0
	setfieldeffectargument 0, 0
	lockall
	msgbox Text_WantToSurf, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, EventScript_UseSurfRelease
	msgbox Text_UsedSurf
	dofieldeffect FLDEFF_USE_SURF
EventScript_UseSurfRelease:
	releaseall
EventScript_UseSurfEnd:
	end

EventScript_CurrentTooFast::
	lockall
	msgbox Text_CurrentTooFast
	releaseall
	end
